export default {
  MODEL_MONK: 'models/cyber-temple-matrix/monk.glb',
  MODEL_HEART: 'models/cyber-temple-matrix/heart.glb',

  SOUND_MONK: '',

  MODEL_BOX_BIG: 'models/cyber-temple-matrix/box_big.glb',
  MODEL_BOX_SMALL: 'models/cyber-temple-matrix/box_small.glb',
  MODEL_CAPSULE: 'models/cyber-temple-matrix/capsule.glb',
  MODEL_CAPSULE_BASE: 'models/cyber-temple-matrix/capsule_base.glb',
  MODEL_FLOOR: 'models/cyber-temple-matrix/floor.glb',
  MODEL_KEY_CARD: 'models/cyber-temple-matrix/key_card.glb',
  MODEL_PILL_RED: 'models/cyber-temple-matrix/pill_red.glb',
  MODEL_RINGS: 'models/cyber-temple-matrix/rings.glb',
  MODEL_ROBOT: 'models/cyber-temple-matrix/robot.glb',
  MODEL_ROBOT_BATTERY: 'models/cyber-temple-matrix/robot_battery.glb',
  MODEL_TERMINAL: 'models/cyber-temple-matrix/terminal.glb',
  MODEL_TERMINAL_BTN: 'models/cyber-temple-matrix/terminal_btn.glb',
  MODEL_TERMINAL_CARD: 'models/cyber-temple-matrix/terminal_card.glb',
  MODEL_TERMINAL_SCREEN: 'models/cyber-temple-matrix/terminal_screen.glb',

  SOUND_AMBIENT: 'sounds/cyber-temple-matrix/ambient.mp3',
  SOUND_CLICK: 'sounds/cyber-temple-matrix/click.mp3',
  SOUND_DROP_CUBE: 'sounds/cyber-temple-matrix/drop_cube.mp3',
  SOUND_ERROR_ROBOT: 'sounds/cyber-temple-matrix/error_robot.mp3',
  SOUND_ERROR_TERMINAL: 'sounds/cyber-temple-matrix/error_terminal.mp3',
  SOUND_GENERATOR_START: 'sounds/cyber-temple-matrix/generator_start.mp3',
  SOUND_INSERT_CARD: 'sounds/cyber-temple-matrix/insert_card.mp3',
  SOUND_PUSH_CAPSULE: 'sounds/cyber-temple-matrix/push_capsule.mp3',
  SOUND_TAKE_BOX: 'sounds/cyber-temple-matrix/take_box.mp3',
  SOUND_TAKE_CARD: 'sounds/cyber-temple-matrix/take_card.mp3',
  SOUND_TAKE_TABLET: 'sounds/cyber-temple-matrix/take_tablet.mp3',
  SOUND_ROBOT_MOVE: 'sounds/cyber-temple-matrix/robot_move.mp3',

  IMAGE_BATTERY: 'images/cyber-temple-matrix/battery.jpg',
  IMAGE_KEY: 'images/cyber-temple-matrix/key.jpg',
  IMAGE_MORF: 'images/cyber-temple-matrix/morf.png',
  IMAGE_RU: 'images/cyber-temple-matrix/ru.jpg',
  IMAGE_RU_DESC: 'images/cyber-temple-matrix/ru_desc.png',

  VIDEO_WALL: 'videos/cyber-temple-matrix/wall.mp4',
}