export default {
  MODEL_BOX_BIG: 'models/box_big.glb',
  MODEL_BOX_SMALL: 'models/box_small.glb',
  MODEL_CAPSULE: 'models/capsule.glb',
  MODEL_CAPSULE_BASE: 'models/capsule_base.glb',
  MODEL_FLOOR: 'models/floor.glb',
  MODEL_KEY_CARD: 'models/key_card.glb',
  MODEL_PILL_RED: 'models/pill_red.glb',
  MODEL_RINGS: 'models/rings.glb',
  MODEL_ROBOT: 'models/robot.glb',
  MODEL_ROBOT_BATTERY: 'models/robot_battery.glb',
  MODEL_TERMINAL: 'models/terminal.glb',
  MODEL_TERMINAL_BTN: 'models/terminal_btn.glb',
  MODEL_TERMINAL_CARD: 'models/terminal_card.glb',
  MODEL_TERMINAL_SCREEN: 'models/terminal_screen.glb',

  SOUND_AMBIENT: 'sounds/ambient.mp3',
  SOUND_AMBIENT_QUEST: 'sounds/ambient_quest.mp3',
  SOUND_CLICK: 'sounds/click.mp3',
  SOUND_DROP_CUBE: 'sounds/drop_cube.mp3',
  SOUND_ERROR_ROBOT: 'sounds/error_robot.mp3',
  SOUND_ERROR_TERMINAL: 'sounds/error_terminal.mp3',
  SOUND_GENERATOR_START: 'sounds/generator_start.mp3',
  SOUND_INSERT_CARD: 'sounds/insert_card.mp3',
  SOUND_PUSH_CAPSULE: 'sounds/push_capsule.mp3',
  SOUND_TAKE_BOX: 'sounds/take_box.mp3',
  SOUND_TAKE_CARD: 'sounds/take_card.mp3',
  SOUND_TAKE_TABLET: 'sounds/take_tablet.mp3',
  SOUND_ROBOT_MOVE: 'sounds/robot_move.mp3',

  IMAGE_BATTERY: 'images/battery.jpg',
  IMAGE_KEY: 'images/key.jpg',
  IMAGE_MORF: 'images/morf.png',
  IMAGE_RU: 'images/ru.jpg',
  IMAGE_RU_DESC: 'images/ru_desc.png',

  VIDEO_WALL: 'videos/wall.mp4',
}
